common: &common
 encoding: utf8
 adapter: postgresql
 username: rootstrap
 password:
 min_messages: WARNING
 host: localhost
 pool: 5

development:
 <<: *common
 port: 5432
 database: rails5_example 

test:
 <<: *common
 host: localhost
 port: 5432
 database: rails5_example_test